# 数据预处理

加载load_iris数据

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

统计学习方法（第二版）p63例子，算法计算结果与书本结果相同，但是sklearn计算出来的结果与书本接近，查看sklearn源码发现sklearn可能出于对值较小的概率相乘容易产生截尾强制转为0的情况，对所有概率计算了log进行放大，最后取exp恢复（但是也会造成一点点精度的损失）

In [5]:
# S=0,M=1,L=2
# X = np.array([[1,0],[1,1],[1,1],[1,0],[1,0],[2,0],[2,1],[2,1],[2,2],[2,2],[3,2],[3,1],[3,1],[3,2],[3,2]])
# y = np.array([-1,-1,1,1,-1,-1,-1,1,1,1,1,1,1,1,-1])

# 朴素贝叶斯估计

In [6]:
def bayesian(X, y, test, smooth=None):
    classlabel_list = sorted(list(set(y)))
    feature_cnt = X.shape[1]
    
    X = X.astype(np.str)
    
    # 存放不同类别样本的下标的list
    classlabel_index_list = []
    
    # 存放先验概率的list
    prior_list = []    
    
    # 总样本个数
    total_cnt = 0
    
    # 存放每个特征维度取值的list
    feature_domain_list = []
    
    # 似然概率字典
    likelihood_dict = {}
    
    # 存放后验概率的list
    posterior_list = []
    
    # 计算不同类别样本总数
    for classlabel in classlabel_list:
        classlabel_index_list.append(np.where(y==classlabel)[0])
    
    # 计算样本总数
    for classlabel_index in classlabel_index_list:
        total_cnt = total_cnt + len(classlabel_index)
                                   
    # 计算先验P(y)概率
    for classlabel_index in classlabel_index_list:
        if smooth == None:
            # 朴素贝叶斯
            prior_list.append(len(classlabel_index)/total_cnt)
        else:
            # 贝叶斯（拉普拉斯平滑）
            prior_list.append((len(classlabel_index)+smooth)/(total_cnt + smooth*feature_cnt))
            
    # 统计每个特征维度的取值可能
    for feature in range(feature_cnt):
        feature_domain_list.append(np.unique(X[:,feature]))
    
    # 计算似然P(X|Y)概率
    for i in range(len(classlabel_index_list)):
        # 属于类别i的样本
        X_condition = X[classlabel_index_list[i]]
        for j in range(len(feature_domain_list)):
            for k in feature_domain_list[j]:
                # 属于第j个特征维度，取值为k的样本
                if smooth == None:
                    # 朴素贝叶斯
                    likelihood_dict[str(i) + '_' + str(j) + '_' + str(k)] = len(np.where(X_condition[:,j]==str(k))[0]) / X_condition.shape[0]
                else:
                    # 贝叶斯（拉普拉斯平滑）
                    likelihood_dict[str(i) + '_' + str(j) + '_' + str(k)] = \
                    (len(np.where(X_condition[:,j]==str(k))[0]) + smooth )/ (X_condition.shape[0] + smooth * len(feature_domain_list[j]))
                
#                 print(str(i) + '_' + str(j) + '_' + str(k), len(np.where(X_condition==str(k))[0]), X_condition.shape[0])
    
    # 计算后验概率
    for i in range(len(classlabel_index_list)):
        feature_independence_pobability = 1
        for j in range(len(feature_domain_list)):
            feature_independence_pobability *= likelihood_dict[str(i) + '_' + str(j) + '_' + str(test[j])]
        posterior_list.append(prior_list[i]*feature_independence_pobability)
        
    return posterior_list

In [7]:
out = bayesian(X, y, np.array([5.4, 3.4, 1.7, 0.2]))
# out = bayesian(X, y, np.array([2,0]))
print(out)
[o / sum(out) for o in out]

[0.00027839999999999994, 0.0, 0.0]


[1.0, 0.0, 0.0]

In [8]:
out = bayesian(X, y, np.array([5.4, 3.4, 1.7, 0.2]), smooth=1)
# out = bayesian(X, y, np.array([2,0]), smooth=1)
print(out)
[o / sum(out) for o in out]

[7.173559979569701e-05, 3.1882488798087556e-08, 2.3911866598565672e-08]


[0.9992228266903519, 0.00044409903408460075, 0.00033307427556345063]

# sklearn 对比

In [9]:
from sklearn.naive_bayes import CategoricalNB

In [10]:
clf = CategoricalNB()
clf.fit(X, y)
y_pred_pro = clf.predict_proba(np.array([5.4, 3.4, 1.7, 0.2]).reshape(1,-1))
# y_pred_pro = clf.predict_proba(np.array([2,0]).reshape(1,-1))
y_pred_pro

array([[9.99820339e-01, 1.21795061e-04, 5.78664316e-05]])